unpackaged/main/default/objects/General_Settings__c/General_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Is used to store org specific configuration.</description>
    <label>General Settings</label>
</CustomObject>

unpackaged/main/default/objects/General_Settings__c/fields/Triggers_Disabled__c.field-meta.xml
<CustomField>
    <fullName>Triggers_Disabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Triggers Disabled</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/GlobalConstants.cls
/**
 * @description Store global constants to be re-used across application.
 **/
public with sharing class GlobalConstants {

    public static final General_Settings__c GLOBAL_SETTINGS {
        get {
            if (GLOBAL_SETTINGS == null) {
                GLOBAL_SETTINGS = General_Settings__c.getOrgDefaults();
            }
            return GLOBAL_SETTINGS;
        }
        private set;
    }

    public static Boolean areTriggersEnabled() {
        return !GLOBAL_SETTINGS?.Triggers_Disabled__c;
    }

    public static final String LC_STATUS_PENDING_DEACTIVATION = 'Pending Deactivation';
    public static final String LC_STATUS_DEACTIVATED = 'Deactivated';
    public static final String LC_STATUS_PENDING_DISABLEMENT = 'Pending Disablement';
    public static final String LC_STATUS_DISABLED = 'Disabled';
}