unpackaged/main/default/objects/Account/fields/Average_NPS_Score__c.field-meta.xml
<CustomField>
    <fullName>Average_NPS_Score__c</fullName>
    <label>Average NPS Score</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Clinical_Practice.recordType-meta.xml
<RecordType>
    <fullName>Clinical_Practice</fullName>
    <active>true</active>
    <label>Clinical Practice</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Average_NPS_Score__c.field-meta.xml
<CustomField>
    <fullName>Average_NPS_Score__c</fullName>
    <label>Average NPS Score</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Lactation_Consultant.recordType-meta.xml
<RecordType>
    <fullName>Lactation_Consultant</fullName>
    <active>true</active>
    <label>Lactation Consultant</label>
</RecordType>

unpackaged/main/default/objects/Patient_Visit_Survey__c/Patient_Visit_Survey__c.object-meta.xml
<CustomObject>
    <label>Patient Visit Survey</label>
    <nameField>
        <displayFormat>PSV-{0000000}</displayFormat>
        <label>Patient Visit Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patient Visit Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Patient_Visit_Survey__c/fields/LC__c.field-meta.xml
<CustomField>
    <fullName>LC__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>LC</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Patient Visit Survey (LC)</relationshipLabel>
    <relationshipName>LC_Visit_Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Patient_Visit_Survey__c/fields/LCP__c.field-meta.xml
<CustomField>
    <fullName>LCP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>LCP</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Patient Visit Surveys(LCP)</relationshipLabel>
    <relationshipName>Patient_Visit_Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Patient_Visit_Survey__c/fields/NPS_Score__c.field-meta.xml
<CustomField>
    <fullName>NPS_Score__c</fullName>
    <label>NPS Score</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/AverageSurveyScoreBatchTestSuite.cls
/**
 * Created by maximelets on 10/07/2024.
 */
@IsTest
private class AverageSurveyScoreBatchTestSuite {
    private static final Id LC_ACCOUNT_RT = Account.getSObjectType()
        .getDescribe()
        .getRecordTypeInfosByDeveloperName()
        .get('Clinical_Practice')
        .getRecordTypeId();
    private static final Id LC_CONTACT_RT = Contact.getSObjectType()
        .getDescribe()
        .getRecordTypeInfosByDeveloperName()
        .get('Lactation_Consultant')
        .getRecordTypeId();
    @TestSetup
    private static void setupData() {
        Account LCPAccount = new Account(Name = 'LCP', RecordTypeId = LC_ACCOUNT_RT);
        insert LCPAccount;
        List<Contact> consultants = new List<Contact>{
            new Contact(FirstName = '1', LastName = '1', RecordTypeId = LC_CONTACT_RT, AccountId = LCPAccount.Id),
            new Contact(FirstName = '2', LastName = '2', RecordTypeId = LC_CONTACT_RT, AccountId = LCPAccount.Id),
            new Contact(FirstName = '3', LastName = '3', RecordTypeId = LC_CONTACT_RT, AccountId = LCPAccount.Id)
        };
        insert consultants;
        List<Patient_Visit_Survey__c> surveys = new List<Patient_Visit_Survey__c>{
            // LC 1 - 60 percents
            new Patient_Visit_Survey__c(NPS_Score__c = 10, LC__c = consultants.get(0).Id, LCP__c = LCPAccount.Id),
            new Patient_Visit_Survey__c(NPS_Score__c = 10, LC__c = consultants.get(0).Id, LCP__c = LCPAccount.Id),
            new Patient_Visit_Survey__c(NPS_Score__c = 10, LC__c = consultants.get(0).Id, LCP__c = LCPAccount.Id),
            new Patient_Visit_Survey__c(NPS_Score__c = 10, LC__c = consultants.get(0).Id, LCP__c = LCPAccount.Id),
            new Patient_Visit_Survey__c(NPS_Score__c = 10, LC__c = consultants.get(0).Id, LCP__c = LCPAccount.Id),
            new Patient_Visit_Survey__c(NPS_Score__c = 10, LC__c = consultants.get(0).Id, LCP__c = LCPAccount.Id),
            new Patient_Visit_Survey__c(NPS_Score__c = 10, LC__c = consultants.get(0).Id, LCP__c = LCPAccount.Id),
            new Patient_Visit_Survey__c(NPS_Score__c = 10, LC__c = consultants.get(0).Id, LCP__c = LCPAccount.Id),
            new Patient_Visit_Survey__c(NPS_Score__c = 6, LC__c = consultants.get(0).Id, LCP__c = LCPAccount.Id),
            new Patient_Visit_Survey__c(NPS_Score__c = 6, LC__c = consultants.get(0).Id, LCP__c = LCPAccount.Id),
            // LC 2
            new Patient_Visit_Survey__c(NPS_Score__c = 10, LC__c = consultants.get(1).Id, LCP__c = LCPAccount.Id),
            new Patient_Visit_Survey__c(NPS_Score__c = 10, LC__c = consultants.get(1).Id, LCP__c = LCPAccount.Id),
            new Patient_Visit_Survey__c(NPS_Score__c = 6, LC__c = consultants.get(1).Id, LCP__c = LCPAccount.Id),
            // LC 3
            new Patient_Visit_Survey__c(NPS_Score__c = null, LC__c = consultants.get(2).Id, LCP__c = LCPAccount.Id),
            new Patient_Visit_Survey__c(NPS_Score__c = 0, LC__c = consultants.get(2).Id, LCP__c = LCPAccount.Id),
            new Patient_Visit_Survey__c(NPS_Score__c = 6, LC__c = consultants.get(2).Id, LCP__c = LCPAccount.Id)
        };

        insert surveys;
    }
    @IsTest
    private static void calculateNPS() {
        System.Test.startTest();
        Database.executeBatch(new AverageSurveyScoreBatch());
        System.Test.stopTest();

        Account LCPAccount = [SELECT Average_NPS_Score__c FROM Account LIMIT 1];
        Assert.isTrue(LCPAccount.Average_NPS_Score__c != null, 'Average Score was updated');
        List<Contact> consultants = [SELECT LastName, Average_NPS_Score__c FROM Contact WHERE AccountId = :LCPAccount.Id];
        for (Contact lc : consultants) {
            System.debug(lc);
            switch on lc.LastName {
                when '1' {
                    Assert.areEqual(60, lc.Average_NPS_Score__c, 'Average Score was updated');
                }
                when '2' {
                    Assert.areEqual(33, lc.Average_NPS_Score__c.intValue(), 'Average Score was updated');
                }
                when '3' {
                    Assert.areEqual(-100, lc.Average_NPS_Score__c, 'Average Score was updated');
                }
                when else {
                    Assert.isFalse(1 == 1, 'Something gone wrong');
                }
            }
        }
    }
}