unpackaged/main/default/objects/Account/recordTypes/Patient.recordType-meta.xml
<RecordType>
    <fullName>Patient</fullName>
    <active>false</active>
    <label>Patient</label>
</RecordType>

unpackaged/main/default/objects/Case/recordTypes/Eligibility.recordType-meta.xml
<RecordType>
    <fullName>Eligibility</fullName>
    <active>true</active>
    <businessProcess>Eligibility</businessProcess>
    <label>Eligibility</label>
</RecordType>

unpackaged/main/default/objects/Flow_Settings__c/fields/Accounts_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Accounts_Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Accounts Enabled</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Flow_Settings__c/fields/Contacts_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Contacts_Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Contacts Enabled</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Eligibility_Status__c.field-meta.xml
<CustomField>
    <fullName>Eligibility_Status__c</fullName>
    <label>Eligibility Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>EligibilityStatus</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/recordTypes/Patient.recordType-meta.xml
<RecordType>
    <fullName>Patient</fullName>
    <active>true</active>
    <businessProcess>Default</businessProcess>
    <label>Patient</label>
</RecordType>

unpackaged/main/default/globalValueSets/EligibilityStatus.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Eligible</fullName>
    </customValue>
    <customValue>
        <fullName>Ineligible</fullName>
    </customValue>
    <masterLabel>Eligibility Status</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/AccountTriggerHandlerTest.cls
/** 
 * @Author: gleb.demidchik@mavenmule.com 
 * @Date: 2025-01-15 
 * @Desc: Unit tests for the Lead trigger handler.
*/
@isTest
public class AccountTriggerHandlerTest {
    public static final String ELIGIBILITY_STATUS_INELIGIBLE = 'Ineligible';
    public static final String ELIGIBILITY_STATUS_ELIGIBLE = 'Eligible';

    @isTest
    public static void ineligibleAccountTest() {
        insert new Flow_Settings__c(SetupOwnerId = UserInfo.getUserId(), Accounts_Enabled__c = false, Contacts_Enabled__c = false);
        Lead lead = TestDataFactory.createLead();
        lead.RecordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('Patient').getRecordTypeId();
        insert lead;

        lead.Eligibility_Status__c = ELIGIBILITY_STATUS_ELIGIBLE;
        update lead;
        lead = [SELECT ConvertedAccountId FROM Lead WHERE Id = :lead.Id];
        
        Case eligibilityCase = TestDataFactory.createCase();
        eligibilityCase.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get(AccountTriggerHandler.ELIGIBILITY_CASE_RECORD_TYPE_NAME).getRecordTypeId();
        eligibilityCase.AccountId = lead.ConvertedAccountId;
        insert eligibilityCase;

        Account accountRecord = [SELECT Eligibility_Status__pc, RecordTypeId FROM Account WHERE Id = :eligibilityCase.AccountId];
        accountRecord.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Patient').getRecordTypeId();
        update accountRecord;
        
        Test.startTest();  
        accountRecord.Eligibility_Status__pc = ELIGIBILITY_STATUS_INELIGIBLE;
        update accountRecord;
        Test.stopTest();

        eligibilityCase = [SELECT Status FROM Case WHERE Id = :eligibilityCase.Id];
        Assert.areEqual(AccountTriggerHandler.ELIGIBILITY_CASE_STATUS_INSURANCE_FINALIZED, eligibilityCase.Status, 'Case must be closed after changing eligibility status on related account');
    }
}