unpackaged/main/default/objects/Contact/fields/LC_Training_Status__c.field-meta.xml
<CustomField>
    <fullName>LC_Training_Status__c</fullName>
    <label>LC Training Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Pending_Deactivation_Since__c.field-meta.xml
<CustomField>
    <fullName>Pending_Deactivation_Since__c</fullName>
    <inlineHelpText>To track when status was changed to Pending Deactivation</inlineHelpText>
    <label>Paused Until</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Not moving on</fullName>
            </value>
            <value>
                <fullName>Moving on to review</fullName>
            </value>
            <value>
                <fullName>Pending committee score</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
            <value>
                <fullName>Pending Deactivation</fullName>
            </value>
            <value>
                <fullName>Enabled</fullName>
            </value>
            <value>
                <fullName>Pending Disablement</fullName>
            </value>
            <value>
                <fullName>Disabled</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
                <isActive>false</isActive>
                <label>Paused</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/TLN_Engagement__c.field-meta.xml
<CustomField>
    <fullName>TLN_Engagement__c</fullName>
    <label>TLN Engagement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TLN_Engagement</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/TLN_Engagement.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>New</fullName>
        <default>true</default>
        <label>New</label>
    </customValue>
    <customValue>
        <fullName>Onboarding</fullName>
    </customValue>
    <customValue>
        <fullName>Training</fullName>
    </customValue>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Paused</fullName>
    </customValue>
    <customValue>
        <fullName>Churned</fullName>
    </customValue>
    <customValue>
        <fullName>Terminated</fullName>
    </customValue>
    <customValue>
        <fullName>Training Completed</fullName>
    </customValue>
    <masterLabel>TLN Engagement</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/ContactTriggerHandler.cls
/**
 * Created by maximelets on 02/08/2024.
 */

public without sharing class ContactTriggerHandler {
    public static void handleBeforeInsertUpdate(List<Contact> newRecords, Map<Id, Contact> oldRecordsMap) {
        for (Contact record : newRecords) {
            Contact oldRecord = oldRecordsMap != null ? oldRecordsMap.get(record.Id) : null;
            setPendingDeactivationTimestamp(record, oldRecord);
        }
    }

    private static void setPendingDeactivationTimestamp(Contact record, Contact oldRecord) {
        Boolean statusChangedToPendingDeactivation = oldRecord?.Status__c != record.Status__c;
        if (statusChangedToPendingDeactivation) {
            if (record.Status__c == GlobalConstants.LC_STATUS_PENDING_DISABLEMENT) {
                record.Pending_Deactivation_Since__c = System.now();
            } else if (record.Status__c != GlobalConstants.LC_STATUS_PENDING_DISABLEMENT) {
                record.Pending_Deactivation_Since__c = null;
            }
        }
    }

    public static void handleBeforeUpdate(List<Contact> newRecords, Map<Id, Contact> oldRecordsMap){
        if(FeatureFlag.isActive('TLN_31485_UPDATETLNENGAGEMENTTOTRAININGC') || System.Test.isRunningTest()) {
            for (Contact record : newRecords) {
                Contact oldRecord = oldRecordsMap != null ? oldRecordsMap.get(record.Id) : null;
                updateTlnEngagementToTrainingCompleted(record, oldRecord);
            }
        }
    }

    private static void updateTlnEngagementToTrainingCompleted(Contact record, Contact oldRecord){
        if (oldRecord.LC_Training_Status__c != record.LC_Training_Status__c && record.LC_Training_Status__c == 'Completed') {
            record.TLN_Engagement__c = 'Training Completed';
        }
    }
}