unpackaged/main/default/objects/Contact/fields/Pending_Deactivation_Since__c.field-meta.xml
<CustomField>
    <fullName>Pending_Deactivation_Since__c</fullName>
    <inlineHelpText>To track when status was changed to Pending Deactivation</inlineHelpText>
    <label>Paused Until</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Not moving on</fullName>
            </value>
            <value>
                <fullName>Moving on to review</fullName>
            </value>
            <value>
                <fullName>Pending committee score</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
            <value>
                <fullName>Pending Deactivation</fullName>
            </value>
            <value>
                <fullName>Enabled</fullName>
            </value>
            <value>
                <fullName>Pending Disablement</fullName>
            </value>
            <value>
                <fullName>Disabled</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
                <isActive>false</isActive>
                <label>Paused</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Grant_Applicant.recordType-meta.xml
<RecordType>
    <fullName>Grant_Applicant</fullName>
    <active>true</active>
    <label>Grant Applicant</label>
</RecordType>

unpackaged/main/default/objects/General_Settings__c/General_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Is used to store org specific configuration.</description>
    <label>General Settings</label>
</CustomObject>

unpackaged/main/default/objects/General_Settings__c/fields/LC_Pending_Deactivation_Max_Days__c.field-meta.xml
<CustomField>
    <fullName>LC_Pending_Deactivation_Max_Days__c</fullName>
    <defaultValue>30</defaultValue>
    <inlineHelpText>Used to store Maximum Number of Days for LC with Pending Deactivation status. When passed, LC will be moved to Deactivated status.</inlineHelpText>
    <label>LC Pending Deactivation Max Days</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/General_Settings__c/fields/Triggers_Disabled__c.field-meta.xml
<CustomField>
    <fullName>Triggers_Disabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Triggers Disabled</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/LCDeactivationBatchTestSuite.cls
/**
 * Created by maximelets on 02/08/2024.
 */

@IsTest
private class LCDeactivationBatchTestSuite {
    @IsTest
    private static void testBehavior() {
        System.Test.startTest();
        Database.executeBatch(new LCDeactivationBatch());
        System.Test.stopTest();

        for (Contact record : [SELECT Id, LastName, Status__c, Pending_Deactivation_Since__c, RecordTypeId FROM Contact]) {
            if (record.RecordTypeId == LCDeactivationBatch.CONTACT_LACTATION_CONSULTANT_RT) {
                if (record.LastName == 'Deactivation') {
                    Assert.areEqual(GlobalConstants.LC_STATUS_DISABLED, record.Status__c, 'Record was deactivated, conditions met.');
                    Assert.areEqual(null, record.Pending_Deactivation_Since__c, 'Record was deactivated, conditions met.');
                } else {
                    Assert.areEqual(GlobalConstants.LC_STATUS_PENDING_DISABLEMENT, record.Status__c, 'No changes to record.');
                    Assert.areNotEqual(null, record.Pending_Deactivation_Since__c, 'Record was deactivated, conditions met.');
                }
            } else {
                //not LC RT
                Assert.isTrue(record.Pending_Deactivation_Since__c != null, 'No changes to record as it is for different record type.');
            }
        }
    }

    @TestSetup
    private static void setupData() {
        insert new General_Settings__c(Triggers_Disabled__c = true);
        List<Contact> contacts = new List<Contact>{
            new Contact(
                LastName = 'Deactivation',
                RecordTypeId = LCDeactivationBatch.CONTACT_LACTATION_CONSULTANT_RT,
                Status__c = GlobalConstants.LC_STATUS_PENDING_DISABLEMENT,
                Pending_Deactivation_Since__c = System.today().addDays(-300)
            ),
            new Contact(
                LastName = 'Not Deactivated Yet',
                RecordTypeId = LCDeactivationBatch.CONTACT_LACTATION_CONSULTANT_RT,
                Status__c = GlobalConstants.LC_STATUS_PENDING_DISABLEMENT,
                Pending_Deactivation_Since__c = System.today().addDays(-1)
            ),
            new Contact(
                LastName = 'Not LC', 
                RecordTypeId = Contact.SObjectType.getDescribe().getRecordTypeInfosByDeveloperName().get('Grant_Applicant').getRecordTypeId(),
                Pending_Deactivation_Since__c = System.today().addDays(-300)
            )
        };
        insert contacts;

        General_Settings__c settings = General_Settings__c.getOrgDefaults();
        settings.LC_Pending_Deactivation_Max_Days__c = 30;
        upsert settings;
    }
}