unpackaged/main/default/objects/Contact/fields/Pending_Deactivation_Since__c.field-meta.xml
<CustomField>
    <fullName>Pending_Deactivation_Since__c</fullName>
    <inlineHelpText>To track when status was changed to Pending Deactivation</inlineHelpText>
    <label>Paused Until</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Not moving on</fullName>
            </value>
            <value>
                <fullName>Moving on to review</fullName>
            </value>
            <value>
                <fullName>Pending committee score</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Deactivated</fullName>
            </value>
            <value>
                <fullName>Pending Deactivation</fullName>
            </value>
            <value>
                <fullName>Enabled</fullName>
            </value>
            <value>
                <fullName>Pending Disablement</fullName>
            </value>
            <value>
                <fullName>Disabled</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
                <isActive>false</isActive>
                <label>Paused</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/recordTypes/Lactation_Consultant.recordType-meta.xml
<RecordType>
    <fullName>Lactation_Consultant</fullName>
    <active>true</active>
    <label>Lactation Consultant</label>
</RecordType>

unpackaged/main/default/classes/LCDeactivationBatch.cls
/**
 * Created by maximelets on 02/08/2024.
 */

public without sharing class LCDeactivationBatch implements Database.Batchable<SObject>, Schedulable {
    private final Integer MAX_DAYS = GlobalConstants.GLOBAL_SETTINGS?.LC_Pending_Deactivation_Max_Days__c != null
        ? GlobalConstants.GLOBAL_SETTINGS?.LC_Pending_Deactivation_Max_Days__c.intValue()
        : 30;
    private final Date DISABLEMENT_DATE_LIMIT = System.today().addDays(-MAX_DAYS);
    @TestVisible
    private static final Id CONTACT_LACTATION_CONSULTANT_RT = Contact.SObjectType.getDescribe()
        .getRecordTypeInfosByDeveloperName()
        .get('Lactation_Consultant')
        .getRecordTypeId();

    public Database.QueryLocator start(Database.BatchableContext context) {
        return Database.getQueryLocator(
            [
                SELECT Id, Status__c, Pending_Deactivation_Since__c
                FROM Contact
                WHERE
                    Status__c = :GlobalConstants.LC_STATUS_PENDING_DISABLEMENT
                    AND Pending_Deactivation_Since__c <= :this.DISABLEMENT_DATE_LIMIT
                    AND RecordTypeId = :CONTACT_LACTATION_CONSULTANT_RT
            ]
        );
    }

    public void execute(Database.BatchableContext context, List<Contact> scope) {
        for (Contact record : scope) {
            record.Pending_Deactivation_Since__c = null;
            record.Status__c = GlobalConstants.LC_STATUS_DISABLED;
        }

        Database.update(scope, false);
    }

    public void finish(Database.BatchableContext context) {
    }

    public void execute(SchedulableContext context) {
        Database.executeBatch(new LCDeactivationBatch());
    }
}